=== ChangeRequest/xml.examples/src/main/resources/complexTypesTnsExample.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xsd:schema
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://github.com/ChangeRequest/xml.examples"
        xmlns:tns="https://github.com/ChangeRequest/xml.examples">
    <xsd:element name="catalog">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="id" type="tns:id" maxOccurs="1" minOccurs="1"/>
                <xsd:element name="items" type="tns:items"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="id">
        <xsd:sequence>
            <xsd:element name="value" type="xsd:unsignedLong"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="items">
        <xsd:sequence>
            <xsd:element name="item" type="item" maxOccurs="unbounded" minOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="item">
        <xsd:sequence>
            <xsd:element name="id" type="id" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="title" type="xsd:string" maxOccurs="1" minOccurs="1"/>
            <xsd:element name="description" type="xsd:string" maxOccurs="1" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== ChangeRequest/xml.examples/src/main/resources/complexTypesTnsExample.xml
<?xml version="1.1" encoding="UTF-8" ?>
<tns:catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="https://github.com/ChangeRequest/xml.examples complexTypesTnsExample.xsd"
             xmlns:tns="https://github.com/ChangeRequest/xml.examples">
    <id>
        <value>1</value>
    </id>
    <items>
        <item>
            <id>
                <value>1</value>
            </id>
            <title>Test Item</title>
        </item>
        <item>
            <id>
                <value>2</value>
            </id>
            <title>Second Item</title>
            <description>with description</description>
        </item>
    </items>
</tns:catalog>
